// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salao;

#nullable disable

namespace SoftwareVisual01.Migrations
{
    [DbContext(typeof(BaseDeDados))]
    [Migration("20221004223318_FuncionarioUpdate")]
    partial class FuncionarioUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Salao.Atendimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("clienteid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataAtendimento")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("funcionarioid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("clienteid");

                    b.HasIndex("funcionarioid");

                    b.ToTable("Atendimento");
                });

            modelBuilder.Entity("Salao.Cliente", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Salao.Funcionario", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Salao.Atendimento", b =>
                {
                    b.HasOne("Salao.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.HasOne("Salao.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioid");

                    b.Navigation("cliente");

                    b.Navigation("funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
