// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salao;

#nullable disable

namespace SoftwareVisual01.Migrations
{
    [DbContext(typeof(BaseDeDados))]
    [Migration("20220926013321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Salao.Atendimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("clienteid")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("funcionarioid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("clienteid");

                    b.HasIndex("funcionarioid");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Salao.Cliente", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroCelular")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Salao.Funcionario", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroCelular")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Salao.Atendimento", b =>
                {
                    b.HasOne("Salao.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.HasOne("Salao.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioid");

                    b.Navigation("cliente");

                    b.Navigation("funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
